module.exports = {
  INIT: ["uint32"],
  VERSION: ["uint32", "PAIRS"],
  OPEN: ["uint32", "string", "uint32", "ATTRS"],
  CLOSE: ["uint32", "string"],
  READ: ["uint32", "string", "uint64", "uint32"],
  WRITE: ["uint32", "string", "uint64", "buffer"],
  LSTAT: ["uint32", "string"],
  FSTAT: ["uint32", "string"],
  SETSTAT: ["uint32", "string", "ATTRS"],
  FSETSTAT: ["uint32", "string", "ATTRS"],
  OPENDIR: ["uint32", "string"],
  READDIR: ["uint32", "string"],
  REMOVE: ["uint32", "string"],
  MKDIR: ["uint32", "string", "ATTRS"],
  RMDIR: ["uint32", "string"],
  REALPATH: ["uint32", "string"],
  STAT: ["uint32", "string"],
  RENAME: ["uint32", "string", "string"],
  READLINK: ["uint32", "string"],
  SYMLINK: ["uint32", "string", "string"],
  STATUS: ["uint32", "uint32", "string", "string"],
  HANDLE: ["uint32", "string"],
  DATA: ["uint32", "buffer"],
  NAME: ["uint32", "NAMES"],
  ATTRS: ["uint32", "ATTRS"],
  EXTENDED: ["uint32", "string"],
  EXTENDED_REPLY: ["uint32"]
};
